articles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('new/', views.new),
    path('create/', views.create),
    path('<int:article_pk>/', views.detail),
    path('<int:article_pk>/delete/', views.delete),
    path('<int:article_pk>/edit/', views.edit),
    path('<int:article_pk>/update/', views.update)
]

pastLifes/urls.py
from django.urls import path
from . import views

app_name = 'pastLifes'

urlpatterns = [
    path('', views.index, name='index'),
    path('showpast/', views.showpast, name='showpast'),
]

reboot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('articles/', include('articles.urls')),
    # path('pastLifes/', include('pastLifes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.

# 20190916 - 1:N Review
# Reporter(1) - Article(N)
# reporter - name
class Reporter(models.Model):
    name = models.CharField(max_length=10)

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # reporter = models.ForeignKey(Reporter, on_delete=models.CASCADE)


# Article(1) - Comment(N)
# comment - content
class Comment(models.Model):
    content = models.CharField(max_length=100)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

manytomany/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    name = models.TextField()

class Patient(models.Model):
    name = models.TextField()
    doctors = models.ManyToManyField(Doctor, related_name='patients')

# class Reservation(models.Model):
#     doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
#     patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

#     def __str__(self):
#         return f'{self.pk} 예약 : {self.doctor.name}의 환자 {self.patient.name}'

onetomany/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    username = models.TextField()

class Article(models.Model):
    title = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

pastLifes/models.py
from django.db import models

# Create your models here.
class PastLife(models.Model):
    name = models.TextField(max_length=10)
    age = models.IntegerField()
    myjob = models.TextField(max_length=50)

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    age = models.IntegerField()
    country = models.CharField(max_length=10)
    phone = models.CharField(max_length=15)
    balance = models.IntegerField()

articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-id')
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.image = request.FILES.get('image')
    article.save()
    return redirect('/articles/')

def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()

    return redirect('/articles/')

def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/edit.html', context)

def update(request,article_pk):
    article = Article.objects.get(pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()

    return redirect(f'/articles/{article_pk}/')

manytomany/views.py
from django.shortcuts import render

# Create your views here.

onetomany/views.py
from django.shortcuts import render

# Create your views here.

pastLifes/views.py
from django.shortcuts import render
from .models import PastLife
from faker import Faker
import requests
from decouple import config

# Create your views here.
def index(request):
    return render(request, 'pastLifes/index.html')

def showpast(request):
    name = request.POST.get('name')
    age = request.POST.get('age')
    if not PastLife.objects.filter(name=name, age=age):
        past = PastLife()
        past.name = name
        past.age = age
        fake = Faker()
        past.myjob = fake.job()
        past.save()
    else:
        past = PastLife.objects.get(name=name, age=age)
    # 직업 결과에 따라, giphy 요청
    job = past.myjob
    api_key = config('GIPHY_API_KEY')
    url = f'http://api.giphy.com/v1/gifs/search?api_key={api_key}&q={job}'
    # 2. 요청 보내기
    response = requests.get(url).json()
    # 3. 응답 결과에서 이미지 url 뽑기
    try:
        image_url = response['data'][0].get('images').get('orignal').get('url')
    except:
        image_url = None
    context = {
        'past':past,
        'image_url':image_url,
    }
    return render(request, 'pastLifes/showpast.html', context)


        

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% block body %}
  <h2>{{ article.title }}</h2><hr>
  {{ article.content }}<br> <hr>
  <img src="{{ article.image.url }}" alt="{{ article.image.name }}">
  <a href="/articles/{{ article.pk }}/delete/">글 삭제하기</a>
  <a href="/articles/{{ article.pk }}/edit/">글 수정하기</a><br>
  <form action="/articles/">
    <input type="submit" value="목록으로">
  </form>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/base.html' %}
{% block body %}
  <form action="/articles/{{ article.pk }}/update/">
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title" value="{{ article.title }}" style="width: 230px"><br>
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea><br>
    <input type="submit">
  </form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block body %}
  <img src="https://cdnimg.melon.co.kr/cm/artistcrop/images/002/61/143/261143_500.jpg?32b7688ac5eb168fa11891d572f7b23d/melon/resize/416/quality/80/optimize" alt="">
  <h1>게시판에 오신걸 환영합니다.</h1>
  <a href="/articles/new/">글 작성하기</a><hr>
    {% for article in articles %}
      {{ article.id }}
      <a href="/articles/{{ article.pk }}">{{ article.title }}</a><br>
    {% endfor %}
{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
  <form action="/articles/create/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title" style="width: 230px"><br>
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10" placeholder="내용을 작성하세요"></textarea><br>
    <label for="image">이미지 : </label>
    <input type="file" name="image" id="image">
    <input type="submit">
    
  </form>
{% endblock %}

pastLifes/templates/pastLifes/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

pastLifes/templates/pastLifes/index.html
{% extends 'pastLifes/base.html' %}
{% block body %}
<h1>당신의 전생을 알려드립니다</h1>
<form action="{% url 'pastLifes:showpast' %}" method="POST">
  {% csrf_token %}
  <label for="name">이름</label>
  <input type="text" id='name' name='name'>
  <label for="age">나이</label>
  <input type="text" id='age' name='age'>
  <input type="submit">
</form>
{% endblock %}

pastLifes/templates/pastLifes/showpast.html
{% extends 'pastLifes/base.html' %}
{% block body %}
<h1>{{past.name}}({{past.age}})님의 전생은 {{past.myjob}}입니다. </h1>

<form action="{% url 'pastLifes:index' %}">
<img src="{{ image_url }}" alt="{{past.myjob}}">
  <input type="submit" value="돌아가기">
</form>
{% endblock %}